[features]
seeds = false
[programs.localnet]
solana_twitter = "7RQuuWWCFVcvZjkh1zPje5hcvhumeRNq6cHcfEtkNsuU"

[programs.devnet]
solana_twitter = "7RQuuWWCFVcvZjkh1zPje5hcvhumeRNq6cHcfEtkNsuU"

[programs.mainnet]
solana_twitter = "7RQuuWWCFVcvZjkh1zPje5hcvhumeRNq6cHcfEtkNsuU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/Wojciech.Jelen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
